### ISSUE TITLE
compileunit source for Mach-O

### ISSUE THREAD

**Issue by wilhuff** [google/bloaty#107]
I'm attempting to debug why the prototype gRPC-C++ framework for iOS is so huge and I've come across the limitation that some of the sources (`armembers`, `compileunits`, and `inlines`) aren't supported with the Mach-O file format.

It would be very helpful to add at least `compileunit` support to help diagnose size problems in frameworks like these.

**Comment by haberman** [comment]
This is supported as of https://github.com/google/bloaty/commit/68b1a10f661ad9f8d92a9a98c8d7421841135cfb!
