### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by learn-more** [google/bloaty#12]
Are there plans to support windows? (both in building the tool and analyzing files)?

With some small tweaks(hacks) it builds inside cygwin,
however running it results in an assertion:

    $ ./bloaty.exe -vvv tests/testdata/linux-x86/01-empty.o
    [segments] AddRange(.text, 0, 0, 34, 0)
    [segments] AddRange(.data, 0, 0, 34, 0)
    [segments] AddRange(.bss, 0, 0, 160000, 0)
    [segments] AddRange(.debug_line, 0, 0, 34, 0)
    [segments] AddRange(.debug_str, 0, 0, 34, 0)
    [segments] AddRange(.comment, 0, 0, 34, 2c)
    [segments] AddRange(.note.GNU-stack, 0, 0, 60, 0)
    [segments] AddRange(.shstrtab, 0, 0, 60, 5c)
    [segments] AddRange(.symtab, 0, 0, 274, 90)
    [segments] AddRange(.strtab, 0, 0, 304, e)
    [segments] AddFileRange([ELF Headers], 0, 34)
    [segments] AddFileRange([ELF Headers], bc, 1b8)
    [segments] AddFileRange([ELF Headers], 0, 0)
    [segments] AddFileRange([Unmapped], 0, 312)
    WARN(2): adding mapping [0, 312] for label [None], this conflicts with existing mapping [34, 60] for label .comment
    WARN: adding mapping [34x, 312x] for label[None], this conflicts with existing mapping [34, 60] for label .comment
    WARN: adding mapping [60x, 312x] for label[None], this conflicts with existing mapping [60, bc] for label .shstrtab
    WARN(2): adding mapping [bc, 312] for label [None], this conflicts with existing mapping [274, 304] for label .symtab
    WARN: adding mapping [274x, 312x] for label[None], this conflicts with existing mapping [274, 304] for label .symtab
    WARN: adding mapping [304x, 312x] for label[None], this conflicts with existing mapping [304, 312] for label .strtab
    [sections] AddRange(.text, 0, 0, 34, 0)
    [sections] AddRange(.data, 0, 0, 34, 0)
    [sections] AddRange(.bss, 0, 0, 160000, 0)
    [sections] AddRange(.debug_line, 0, 0, 34, 0)
    [sections] AddRange(.debug_str, 0, 0, 34, 0)
    [sections] AddRange(.comment, 0, 0, 34, 2c)
    [sections] AddRange(.note.GNU-stack, 0, 0, 60, 0)
    [sections] AddRange(.shstrtab, 0, 0, 60, 5c)
    [sections] AddRange(.symtab, 0, 0, 274, 90)
    [sections] AddRange(.strtab, 0, 0, 304, e)
    [sections] AddFileRange([ELF Headers], 0, 34)
    WARN: adding mapping [34x, 34x] for label[ELF Headers], this conflicts with existing mapping [34, 60] for label .comment
    WARN: adding mapping [60x, 34x] for label[ELF Headers], this conflicts with existing mapping [60, bc] for label .shstrta                                                                                                                                              b
    [sections] AddFileRange([ELF Headers], bc, 1b8)
    WARN: adding mapping [274x, 274x] for label[ELF Headers], this conflicts with existing mapping [274, 304] for label .sym                                                                                                                                              tab
    WARN: adding mapping [304x, 274x] for label[ELF Headers], this conflicts with existing mapping [304, 312] for label .str                                                                                                                                              tab
    [sections] AddFileRange([ELF Headers], 0, 0)
    [sections] AddFileRange([Unmapped], 0, 312)
    WARN: adding mapping [0x, 312x] for label[Unmapped], this conflicts with existing mapping [0, 34] for label [ELF Headers                                                                                                                                              ]
    WARN: adding mapping [34x, 312x] for label[Unmapped], this conflicts with existing mapping [34, 60] for label .comment
    WARN: adding mapping [60x, 312x] for label[Unmapped], this conflicts with existing mapping [60, bc] for label .shstrtab
    WARN: adding mapping [bcx, 312x] for label[Unmapped], this conflicts with existing mapping [bc, 274] for label [ELF Head                                                                                                                                              ers]
    WARN: adding mapping [274x, 312x] for label[Unmapped], this conflicts with existing mapping [274, 304] for label .symtab
    WARN: adding mapping [304x, 312x] for label[Unmapped], this conflicts with existing mapping [304, 312] for label .strtab
    assertion "current != UINTPTR_MAX" failed: file "src/bloaty.cc", line 1040, function: static void bloaty::RangeMap::Comp                                                                                                                                              uteRollup(const std::vector<const bloaty::RangeMap*>&, const string&, int, Func) [with Func = bloaty::Bloaty::ScanAndRol                                                                                                                                              lupFile(const bloaty::InputFile&, bloaty::Rollup*)::Maps::ComputeRollup(const string&, int, bloaty::Rollup*)::<lambda(co                                                                                                                                              nst std::vector<std::basic_string<char> >&, uint64_t, uint64_t)>; std::string = std::basic_string<char>]
    Aborted (core dumped)

Cygwin / g++ versions:

    $ uname -a
    CYGWIN_NT-10.0-WOW DEV1 2.6.0(0.304/5/3) 2016-08-31 14:27 i686 Cygwin

    $ g++ --version
    g++ (GCC) 5.4.0
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Here are the (hack)-fixes that worked for me to get it to build:

     Makefile               | 2 +-
     src/bloaty.cc          | 4 ++++
     third_party/googletest | 0
     third_party/re2        | 0
     4 files changed, 5 insertions(+), 1 deletion(-)

    diff --git a/Makefile b/Makefile
    index 03ba10c..de19bd2 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -3,7 +3,7 @@
     
     # Disable -Wsign-compare because StringPiece currently unhelpfully defines
     # size() as ssize_t instad of size_t.
    -CXXFLAGS=-std=c++11 -ffunction-sections -fdata-sections -Wall -Wno-sign-compare -g -I third_party/re2 -I. -Isrc -O2
    +CXXFLAGS=-std=gnu++11 -ffunction-sections -fdata-sections -Wall -Wno-sign-compare -g -I third_party/re2 -I. -Isrc -O2
     RE2_H=third_party/re2/re2/re2.h
     
     ifeq ($(shell uname), Darwin)
    diff --git a/src/bloaty.cc b/src/bloaty.cc
    index 52ca820..4d8d073 100644
    --- a/src/bloaty.cc
    +++ b/src/bloaty.cc
    @@ -41,6 +41,10 @@
     #include "re2/re2.h"
     #include <assert.h>
     
    +#ifdef __CYGWIN__
    +#define WEXITED         0
    +#endif
    +
     #include "bloaty.h"
     //#include "base/init_google.h"
     
    diff --git a/third_party/googletest b/third_party/googletest
    --- a/third_party/googletest
    +++ b/third_party/googletest
    @@ -1 +1 @@
    -Subproject commit a2b8a8e07628e5fd60644b6dd99c1b5e7d7f1f47
    +Subproject commit a2b8a8e07628e5fd60644b6dd99c1b5e7d7f1f47-dirty
    diff --git a/third_party/re2 b/third_party/re2
    --- a/third_party/re2
    +++ b/third_party/re2
    @@ -1 +1 @@
    -Subproject commit 9efd0dfacc81cc279e135a0e092ff5e9c1d20637
    +Subproject commit 9efd0dfacc81cc279e135a0e092ff5e9c1d20637-dirty

And for re2:

     Makefile | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

    diff --git a/Makefile b/Makefile
    index 411e551..9d8837c 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -17,7 +17,7 @@ CXX?=g++
     CXXFLAGS?=-O3 -g
     LDFLAGS?=
     # required
    -RE2_CXXFLAGS?=-std=c++11 -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I. $(CCICU) $(CCPCRE)
    +RE2_CXXFLAGS?=-std=gnu++11 -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I. $(CCICU) $(CCPCRE)
     RE2_LDFLAGS?=-pthread $(LDICU) $(LDPCRE)
     AR?=ar
     ARFLAGS?=rsc

To get gtest to play nice with cygwin, the makefile generator has to be manually specified for cmake (it ran visual studio generators by default).

I am by no means an expert with makefiles, so these hackfixes might not work for other platforms!

**Comment by haberman** [comment]
I would love to have Windows support, both for building/running on Windows and for analyzing Windows executables.

I'd be happy to take patches to make Bloaty compile on Cygwin and/or MSVC, and any bugfixes for those platforms. I'd also be happy to take patches that enable automated Windows testing on AppVeyor.

I would be curious to know why Cygwin requires `-gnu++11` instead of `c++11`.

**Comment by learn-more** [comment]
In that case the first step (imo) would be to add CMake support,
so that we do not have to use cygwin to build on windows.

(I am suggesting CMake because both dependencies support that).

**Comment by haberman** [comment]
Sounds good. I don't know anything about CMake, but all of that sounds great and patches are welcome!

I think I would prefer to keep the existing Makefile also, so that CMake is not a hard dependency on Linux / OS X.

**Comment by learn-more** [comment]
After looking into it some more:

Creating a (working) cmake configuration for windows/msvc is fairly simple, but then some problems with some of the design choices present themselves:
* Minimum version is visual studio 2015 (because of `constexpr`)
* c++filt does not exist on windows, so that mechanism wont fly.
* Without cygwin, the fork / pipe kinda functions are not going to work on windows.

For the demangling, maybe `__cxa_demangle` could be used? (and preferably as library, so that windows can use it as well!)

One minor issue:
msvc is choking on the construction from BuildActionBuf:
`syntax error: identifier 'IndexSequence<,unsigned int, ?? >'	src\dwarf.cc:1353`

**Comment by haberman** [comment]
Thanks for looking into it!

- How many people have VS2015? It is unreasonable to require VS2015?
- How many changes are required to support an earlier version of VS? I don't think there is anywhere that `constexpr` is integral to the design of Bloaty.
- Yes definitely we'd need some other way of demangling on Windows. It looks like [there is a `UnDecorateSymbolName()` function available](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681400(v=vs.85).aspx).
- Even on Linux it would be nice to link in the demangler instead of shelling out. I bet we could extract the demangling code from LLVM [llvm/lib/Demangle/ItaniumDemangle.cpp](https://github.com/llvm-mirror/llvm/blob/master/lib/Demangle/ItaniumDemangle.cpp) to avoid shelling out to `c++filt`.
- fork/pipe are only necessary if we're shelling out, but if we have native file readers on for both files and symbols, that shouldn't be a problem.

Hmm, it's hard to know what MVSC is complaining about in BuildActionBuf. I have a virtual machine with Windows installed but I'm having troubles using the community edition of MSVC.

**Comment by learn-more** [comment]
* VS2015 is not unreasonable, however I do not have that at home.
* VS2013 should be reasonable to support, constexpr should be removed and it looks like some vararg template constructions are not entirely supported.
* UnDecorateSymbolName is an option on windows, however it will only demangle MSVC symbols.

I have cloned your repository, added the initial cmake + appveyor stuff in it, and gave you push access (so that you can test stuff).

**Comment by Phyllostachys** [comment]
If it adds anything to this conversation, I was able to get everything to build in msys2 + mingw-w64, besides needing to define WEXITED. I need to do some more to see if it actually works and I'm not really sure why I was expecting it to run on PE files (duh, on my part). It does work pretty nicely on my ARM elf files though.

**Comment by learn-more** [comment]
This might be a better first step then!

Initially I tried with cygwin because I did not know that msys2 has support for popen and that kinda stuff,
but the cygwin builds crashed when testing it.
That is why I moved on to trying msvc.

@Phyllostachys : Are the cmake files in https://github.com/learn-more/bloaty needed at all to get this working? (I assume not)

**Comment by Phyllostachys** [comment]
Correct, I didn't use any cmake files, just the makefile that comes with the repo. I think I found this issue after that fact or else I would have tried those too.

**Comment by parbo** [comment]
I'd like to be able to use bloaty to analyze android elf binaries on Windows.  I'm getting these errors: `Command line error D8004: '/W' requires an argument`

**Comment by andrew-donnell** [comment]
Any tips on building on Windows? I used cygwin to clone, but I'm running into issues building in MSVS. I keep getting:
`Error D8004: '/W' requires an argument or`
`Error D8021: 'invalid numeric argument '/Wno-sign-compare'.`

**Comment by andrew-donnell** [comment]
> I'd like to be able to use bloaty to analyze android elf binaries on Windows. I'm getting these errors: `Command line error D8004: '/W' requires an argument`

@parbo I had the same issue. I was able to resolve in VS by going into properties and adding an argument (could also be done by modifying the cmake .txt file) but then I ran into the `Error D8021: 'invalid numeric argument '/Wno-sign-compare'` issue. When I took that out, all hell broke loose 😝

**Comment by parbo** [comment]
@andrew-donnell I solved it by building bloaty in Ubuntu in WSL instead.

**Comment by learn-more** [comment]
@haberman this is solved now
