### ISSUE TITLE
Demangler can't demangle some symbols

### ISSUE THREAD

**Issue by kkaefer** [google/bloaty#124]
Over in mapbox-gl-native, we're using among others this symbol:

`_ZZN3jni17NativeMethodMakerIMZNS_30NativePeerMemberFunctionMethodIMN4mbgl7android9LineLayerEFvR7_JNIEnvxxEXadL_ZNS4_26setLineTranslateTransitionES6_xxEEEclIS4_S4_vEEDaRKNS_5FieldIT0_xEEEUlS6_NS_6ObjectIS4_EExxE_KFvS6_SI_xxEJEEclISJ_EESB_PKcRKT_E6method`

Unfortunately, the demangler included in bloaty can't demangle this symbol, so it can't aggregate them with similar symbols. `c++filt` can't demangle it either, but http://demangler.com can.

**Comment by haberman** [comment]
Do you get this problem with `-d fullsymbols` also? I suspect `-d fullsymbols` will work.

I'm guessing this is a result of the incomplete C++11 support in the Google demangler. The Google demangler was recently released as part of ABSL:

https://github.com/abseil/abseil-cpp/blob/master/absl/debugging/internal/demangle.cc

I wonder if it would make sense to re-file this bug there.

**Comment by kkaefer** [comment]
`-d fullsymbols` works. Thank you!
