### ISSUE TITLE
Debugging stripped MachO binaries?

### ISSUE THREAD

**Issue by jfirebaugh** [google/bloaty#128]
As far as I can tell, the README section ["Debugging Stripped Binaries"](https://github.com/google/bloaty#debugging-stripped-binaries) applies only to ELF binaries. MachO does not seem to have an equivalent to `.note.gnu.build-id`, and Apple's ld errors if given a `--build-id` option.

Is there any other way to get meaningful bloaty output from a stripped MachO binary + .dSYM pair? Using an unstripped binary is problematic; I've seen a String Table section occupying almost 50% of the unstripped binary size, skewing the output.

(A minor quirk of what is otherwise an invaluable tool. Thanks for continuing to work on bloaty; it seems to have gotten better and better each time I find myself using it!)

**Comment by jfirebaugh** [comment]
Thanks for #133. I'm a bit confused by [this TODO](https://github.com/google/bloaty/pull/133/files#diff-04c6e90faac2675aa89e2176d2eec7d8R331) though. Without DWARF support, it's still not possible to profile a stripped MachO binary via the .dSYM, right?

**Comment by haberman** [comment]
I take it back, `dsymutil` *does* appear to put a symbol table in `.dSYM`. This works as expected:

```
$ strip bloaty
$ dsymutil bloaty
$ $ ./bloaty --debug-file bloaty.dSYM/Contents/Resources/DWARF/bloaty  bloaty -d symbols
```

I should update the docs accordingly. Maybe this means I can also enable `-d compileunits` for Mach-O!
