### ISSUE TITLE
Doesn't build on ubuntu 18.04

### ISSUE THREAD

**Issue by YesserLab** [google/bloaty#131]
cmake fails in the configuration:
➜  bloaty-master cmake .
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
fatal: not a git repository (or any of the parent directories): .git
CMake Warning (dev) at CMakeLists.txt:29 (add_subdirectory):
  The source directory
    /home/yesser/Desktop/bloaty-master/third_party/re2
  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:30 (add_subdirectory):
  The source directory

    /home/yesser/Desktop/bloaty-master/third_party/capstone

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:31 (add_subdirectory):
  add_subdirectory given source "third_party/protobuf/cmake" which is not an
  existing directory.

-- Performing Test SUPPORTS_COLOR_ALWAYS
-- Performing Test SUPPORTS_COLOR_ALWAYS - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/home/yesser/Desktop/bloaty-master/CMakeFiles/CMakeOutput.log".
See also "/home/yesser/Desktop/bloaty-master/CMakeFiles/CMakeError.log".

[CMakeOutput.log](https://github.com/google/bloaty/files/2213083/CMakeOutput.log)

**Comment by PoroCYon** [comment]
You need the submodules:

```
git submodule update --init --recursive
```

**Comment by YesserLab** [comment]
Oh, I realized what the problem is. Downloading the zip file from github doesn't contain the repo information. Cloning it, however, got it working :)
