### ISSUE TITLE
DWARF data is too new for us

### ISSUE THREAD

**Issue by aaronovz1** [google/bloaty#139]
I have a binary which has a mixture of compilation unit versions (2, 3, and 4). bloaty seems to only support up to 2 and will not partial process the binary if it has a mixture.

Any idea on when support for versions greater than 2 will happen?

**Comment by haberman** [comment]
Oops, I thought I had updated everything for DWARF 4. But it looks like AddressRanges still only respects up to 2.

https://github.com/google/bloaty/blob/feaca236c63cf25efdac1b1c9b3aeb6878aa74fd/src/dwarf.cc#L436

This should be an easy fix.
