### ISSUE TITLE
Set debug info on MacOS

### ISSUE THREAD

**Issue by andrew-donnell** [google/bloaty#147]
@haberman What compiler flags do I need enabled to get debug info on MacOS? Everything I can find tells me it should be `-g`, but that doesn't seem to be working - maybe it is a CMake flag that needs ot be enabled? 

To be more concrete than theoretical, what would I need to add to the `cmake` or `make` commands on the bloaty executable so that I can run `./bloaty bloaty -d compileunits` without an error? 

Thanks! :)

**Comment by haberman** [comment]
Sorry for the slow reply. You should find the info you need here: https://github.com/google/bloaty#mach-o

If that doesn't work feel free to re-open.

**Comment by ericoporto** [comment]
Updated link

https://github.com/google/bloaty/blob/main/doc/using.md#mach-o

> Mach-O files always have build IDs (as far as I can tell),
> so no special configuration is needed to make sure you get
> them.
> 
> Mach-O puts debug information in separate files which you
> can create with `dsymutil`:
> 
> ```
> $ dsymutil bloaty
> $ strip bloaty  (optional)
> $ ./bloaty -d symbols --debug-file=bloaty.dSYM/Contents/Resources/DWARF/bloaty bloaty
> ```

Special attention to the need to 

- it's using bloaty to inspect itself, if you installed from brew (`brew install bloaty`) you obviously don't want to do this
- you probably want to build your binary with something like relwithdebinfo
- you NEED to use `dsymutil` on your binary

My example command line usage is

```
bloaty -d compileunits -n 0 -s file --debug-file=mybin.dSYM/Contents/Resources/DWARF/mybin mybin  > report.txt
```

which should give a more actionable report like

```
    FILE SIZE        VM SIZE    
 --------------  -------------- 
   2.0%   136Ki   1.4%   136Ki    myfile.c
```
