### ISSUE TITLE
`--debug-file` flag seems broken

### ISSUE THREAD

**Issue by agrieve** [google/bloaty#148]
```
$ ../../bloaty/bloaty --debug-file out-gn/Release/lib.unstripped/libmonochrome.so out-gn/Release/libmonochrome.so -n 1000 -s file -w -d inlines out/Release/libchrome.so
bloaty: no debug info
```

If I run pointing at `out-gn/Release/lib.unstripped/libmonochrome.so` directly, then the tools works fine:
```
# Works:
../../bloaty/bloaty out-gn/Release/lib.unstripped/libmonochrome.so -n 1000 -s file -w -d inlines
```

**Comment by haberman** [comment]
Do you get the same result with `-d compileunits`?

`-d inlines` needs some work. I'm actually interested in giving better, specialized output for this data source that captures the fact that inlines are inherently nested in the binary. I want to generate output that works with `pprof` and visualizes that way. Are you interested in being a trial custom for this and giving feedback?

**Comment by agrieve** [comment]
Neat idea! Might map quite well to pprof (so you can view it top down or bottom-up). I'd certainly be happy to try it out if it becomes a thing :).

As for this bug, I missed in my own paste of what I ran, that I had specified the stripped .so twice! (well actually, two different .so files). Proper invocation worked fine:
```
bloaty --debug-file=out-gn/Release/lib.unstripped/libmonochrome.so out-gn/Release/libmonochrome.so -n 1000 -s file -w -d inlines
```
