### ISSUE TITLE
Split DWARF support

### ISSUE THREAD

**Issue by SaschaZorn** [google/bloaty#156]
Is it planed to add [Split DWARF](https://gcc.gnu.org/wiki/DebugFission) support to bloaty? 

-d compileunits does not work for my build where debug info is outsourced into external .dwo files. 

```
    VM SIZE                                                          FILE SIZE
 --------------                                                    --------------
   0.0%       0 [section .debug_ranges]                             4.46Mi  26.0%
   0.0%       0 [section .debug_addr]                               4.41Mi  25.7%
   0.0%       0 [section .debug_line]                               2.78Mi  16.2%
   0.0%       0 [section .gdb_index]                                2.78Mi  16.2%
  77.2%  1.52Mi [DWARF is missing filename]                         1.86Mi  10.9%
```

_readelf --debug-dump_ looks like this:
```
Contents of the .debug_info section:

  Compilation Unit @ offset 0x0:
   Length:        0x30 (32-bit)
   Version:       4
   Abbrev Offset: 0x0
   Pointer Size:  8
 <0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <c>   DW_AT_ranges      : 0x106d0
    <10>   DW_AT_low_pc      : 0x0
    <18>   DW_AT_stmt_list   : 0x0
    <1c>   DW_AT_GNU_dwo_name: (indirect string, offset: 0x0): product/CMakeFiles/product_module_objlib.dir/product.cpp.dwo
    <20>   DW_AT_comp_dir    : (indirect string, offset: 0x40): /develop/git1/gen/opt
    <24>   DW_AT_GNU_pubnames: 1
    <24>   DW_AT_GNU_addr_base: 0x0
    <28>   DW_AT_GNU_dwo_id  : 0xdb38d234acb62a94
    <30>   DW_AT_GNU_ranges_base: 0x0

```

**Comment by Trass3r** [comment]
Also these can be combined into .dwp files pretty much like .pdbs

**Comment by haberman** [comment]
Looks like Bloaty still doesn't support this. It shouldn't be too hard to add, but it's also not totally trivial.

Bloaty does support separate debug files with `--debug-file`: https://github.com/google/bloaty/blob/master/doc/using.md#debugging-stripped-binaries

However it doesn't understand the case of splitting a single compileunit's DWARF info across two different files.

**Comment by haberman** [comment]
It looks like the split DWARF stuff got standardized in DWARF 5, which has a different representation:

```
0x00000014: DW_TAG_skeleton_unit
              DW_AT_stmt_list   (0x00000000)
              DW_AT_str_offsets_base    (0x00000008)
              DW_AT_comp_dir    ("/tmp")
              DW_AT_GNU_pubnames        (true)
              DW_AT_dwo_name    ("foo.dwo")
              DW_AT_low_pc      (0x0000000000000000)
              DW_AT_high_pc     (0x0000000000000049)
              DW_AT_addr_base   (0x00000008)
```

**Comment by Trass3r** [comment]
Dwarf 5 splitting is even less supported by tools than the previous one, e.g. https://sourceware.org/bugzilla/show_bug.cgi?id=26219

**Comment by ayermolo** [comment]
Hi.
Is there a plan to add support?

**Comment by haberman** [comment]
I implemented support for GNU (pre-DWARF 5) split DWARF in https://github.com/google/bloaty/pull/290

Could you give a try and see if it works for you? It worked for me when I used `-gsplit-dwarf` locally.

**Comment by ayermolo** [comment]
@haberman Thanks for looking into it, sorry for late reply, I forwarded it to a person who was having issues with it internally.
