### ISSUE TITLE
sort in alphabetical order

### ISSUE THREAD

**Issue by xnlcasad** [google/bloaty#158]
I would have an use case where sorting by alphabetical order of the compileunits (or symbols) would make sense instead of using symbols' size.

For instance, when several compile units are part of a "component" and we'd like to easily compute the overall size of the component itself. Having all symbols listed alphabetically would make it easier to pick those that are logically related by having similar component prefix in their name.

This is a feature request/enhancement. Bloaty is great already.

**Comment by haberman** [comment]
I think you will get better results if you set up your "component" as a custom data source. See: https://github.com/google/bloaty#custom-data-sources

> This is a feature request/enhancement. Bloaty is great already.

Thank you, I am glad you like Bloaty!
