### ISSUE TITLE
Optimized builds and compileunits

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [google/bloaty#181]
Hi everyone

bloaty is a pretty cool tool. I'm trying to use it in an embedded environment with elf files and have a question:

When I use bloaty with a debug build 
```
		set( CMAKE_C_FLAGS_DEBUG "-O0 -g -DDEBUG" CACHE STRING "Flags used by the compiler during debug builds." FORCE )
		set( CMAKE_CXX_FLAGS_DEBUG "-O0 -g -DDEBUG" CACHE STRING "Flags used by the compiler during debug builds." FORCE )
		set( CMAKE_ASM_FLAGS_DEBUG "-O0 -g -DDEBUG" CACHE STRING "Flags used by the compiler during debug builds." FORCE )
```
I get an overview of the memory consumption of my compilation units when I run bloaty with 
`-d compileunits`.

When I use bloaty with a release build with debug symbols enabled bloaty does not resolve the memory consumption of the compilation units:
```
		set( CMAKE_C_FLAGS_RELEASE "-Os -g -DNDEBUG" CACHE STRING "Flags used by the compiler during release builds." FORCE )
		set( CMAKE_CXX_FLAGS_RELEASE "-Os -g -DNDEBUG" CACHE STRING "Flags used by the compiler during release builds." FORCE )
		set( CMAKE_ASM_FLAGS_RELEASE "-Os -g -DNDEBUG" CACHE STRING "Flags used by the compiler during release builds." FORCE )
```

Is it possible to get a resolution of memory consumption of compilation units when optimizing the build. If yes, how do I do it?

Thanks in advance for the help.
Nikolai

**Comment by haberman** [comment]
Hi, I'm glad you like Bloaty!

Usually `-g` is sufficient to make `compileunits` work. Enabling optimization with the `-Os` flag should not break it.

Without more information it's hard to say what is going on here.

**Comment by Nikolai-Hlubek** [comment]
Dear Joshua
Thanks for confirming that - g should work on optimized builds.

Indeed it works now. I had an issue with my tool chain and after I fixed it I now get the expected results from bloaty.

Best regards and keep up the good work, 
Nikolai
