### ISSUE TITLE
Gcov profiling support?

### ISSUE THREAD

**Issue by AIK13** [google/bloaty#186]
Hi,
I want to compile Bloaty with` -fprofile-arcs -ftest-coverage` passed into gcc and g++ to enable gcov coverage support. How can I do this? I don’t see an option for that in the CMakeList or configure files.

**Comment by haberman** [comment]
Bloaty will use all of the standard CMake flags for CFLAGS/CXXFLAGS. So I think you could do either:

```
$ cmake -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" ...
```

```
$ CXXFLAGS="-fprofile-arcs -ftest-coverage" cmake ...
```
