### ISSUE TITLE
bloaty shouldn't open all input files simulateously

### ISSUE THREAD

**Issue by jchl** [google/bloaty#192]
bloaty appears to keep all of its input files open for the duration of its execution.  As a result, when running bloaty on a very large number of input files, you can run up against open file limitations:

```
$ bloaty *.so.0.0.0
bloaty: couldn't open file 'libFoo.so.0.0.0': Too many open files
```

It would be better if bloaty would close each of the input files immediately after `mmap`ing them, so as not to run into this limit.

**Comment by haberman** [comment]
> It would be better if bloaty would close each of the input files immediately after mmaping them

I believe Bloaty does close each `fd` immediately after `mmap`ing it. Here is an `strace` of running Bloaty on itself:

```
openat(AT_FDCWD, "bloaty", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0750, st_size=49607296, ...}) = 0
mmap(NULL, 49607296, PROT_READ, MAP_SHARED, 3, 0) = 0x7f6ab5fee000
close(3)                                = 0
```

However it does appear that Bloaty will not `munmap()` the files until it is finished scanning all files. Maybe that is what is triggering the error.

I agree Bloaty should `munmap()` each file as soon as it is done scanning it.

**Comment by jchl** [comment]
Sorry, my bad.  I'd switched to using a 64-bit binary to get around the 32-bit limitation described in https://github.com/google/bloaty/issues/190, but I'd forgotten that I'd built that from an ancient version of the bloaty code.

I do not see the error when running with the latest code.

I agree that `munmap`ing the files as soon as possible would be better if bloaty's design makes that feasible, though the current behavior doesn't seem to be causing me any problems.
