### ISSUE TITLE
Support for mach-o with bitcode

### ISSUE THREAD

**Issue by okhowang** [google/bloaty#205]
I build an iOS static library with debug info, but bloaty couldn't read debug info from library or object file.
```shell
$ bloaty -d symbols unity_0_cxx.o
bloaty: unknown file type for file 'unity_0_cxx.o'

$ bloaty -d symbols armv7 
    FILE SIZE        VM SIZE    
 --------------  -------------- 
 100.0%  46.5Mi   NAN%       0    [AR Non-ELF Member File]
   0.0%     188   NAN%       0    [AR Headers]
 100.0%  46.5Mi 100.0%       0    TOTAL

$ file unity_0_cxx.o
unity_0_cxx.o: LLVM bitcode, wrapper arm
$ file armv7 
armv7: current ar archive
```

**Comment by haberman** [comment]
I don't think this file is a Mach-O file at all, I think it's using Bitcode as the main file format.

This could be interesting to add to Bloaty, but it would be a big project as it's an entirely new file format.
