### ISSUE TITLE
Create a GitHub release for Bloaty

### ISSUE THREAD

**Issue by Yamakaky** [google/bloaty#22]
https://aur.archlinux.org/packages/bloaty-git/

BTW, it would be cool to make a github release.

**Comment by haberman** [comment]
Cool, thanks for the note!

It sounds like your request from this issue is to have a GitHub release. I'll retitle the issue accordingly.

**Comment by Yamakaky** [comment]
Sorry, changed my mind while writing it ^^

**Comment by dtzWill** [comment]
+1 :)

**Comment by AlekSi** [comment]
That's also required for Homebrew (Homebrew/homebrew-core#11803).

**Comment by chocol4te** [comment]
Any update on this?

**Comment by haberman** [comment]
I finally got to the point where I was comfortable making a release. Bloaty 1.0 is now available here: https://github.com/google/bloaty/releases/tag/v1.0
