### ISSUE TITLE
travis-ci.org shutting down

### ISSUE THREAD

**Issue by learn-more** [google/bloaty#232]
Currently integrations still point at travis-ci.org, this should be updated to travis-ci.com
However it seems that they are not offering free plans for open source anymore?
https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567

Might make sense to migrate to github builds.

**Comment by compnerd** [comment]
There are now builds on GitHub Actions, tests remain to be enabled.  I think that the migration might not be too difficult.  This gave an opportunity to expand the testing coverage as well, which has already netted some fixes that are nice (at least IMO).

**Comment by haberman** [comment]
Fixed by https://github.com/google/bloaty/pull/265.
