### ISSUE TITLE
Files >2GB not supported

### ISSUE THREAD

**Issue by mrichtarsky** [google/bloaty#24]
```
$ bloaty large_binary
bloaty: Unknown file type: large_binary
bloaty: error calling munmap(): Invalid argument
```

This happens since `StringPiece` from `re2`, which is used to point to the binary data, stores the length as an `int` and overflows. This subsequently leads to the failure of `CHECK_RETURN(data_.size() >= EI_NIDENT);` in `elf.cc`.

Latest `re2` sources seem to correctly use `size_t` for length, perhaps they could be used:
https://github.com/google/re2/blob/master/re2/stringpiece.h

**Comment by haberman** [comment]
I just submitted a pull request to update RE2. Want to pull it and see if it fixes your problem?

https://github.com/google/bloaty/pull/27

**Comment by haberman** [comment]
The pull request is submitted. Please let me know if it fixes the problem for you.

**Comment by mrichtarsky** [comment]
Works now, thanks for the quick fix!
