### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [google/bloaty#25]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/google/bloaty/blob/dafb84b6a189182a302fec165df7ddbec657c1b5/src/main.cc#L19 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider effects for uncaught/unhandled exceptions?

**Comment by haberman** [comment]
We do not use exceptions per the Google style guide: https://google.github.io/styleguide/cppguide.html#Exceptions

Some of the standard library functions can throw exceptions if you call them incorrectly. But I see this as being like assertion failures: they can and should cause the program to abort. I don't see any benefit to catching exceptions in `main()`.

**Comment by elfring** [comment]
Which behaviour do you expect from [the software implementation](https://stackoverflow.com/questions/8311457/are-destructors-called-after-a-throw-in-c "Expectations for the std::terminate() function?") if a C++ exception will not be caught/handled there?

**Comment by haberman** [comment]
All I care is that the exception is printed to the screen and the program exits. I don't care if destructors are called.

**Comment by elfring** [comment]
I would care more if the desired destructors are called also before program termination.

**Comment by haberman** [comment]
Why does that matter? The OS will clean up any resources we were holding. I can't see any reason that it helps us to ensure destructors are called.

**Comment by elfring** [comment]
Can destructors contain special functionality where it is important to execute the corresponding code also at the end?

**Comment by haberman** [comment]
Bloaty has some destructors that perform cleanup. For example this destructor will call `munmap()`: https://github.com/google/bloaty/blob/master/src/bloaty.cc#L1185

But all of these cleanup functions will be performed automatically by the OS when the program exits. There is really no benefit to manually cleaning up resources that the OS will clean up for you anyway.
