### ISSUE TITLE
Missing debug info while looking into ios ipa's unix exec file

### ISSUE THREAD

**Issue by gouravsinghal92** [google/bloaty#288]
I have an ipa with me. Made it .zip and extracted he contents out of it. it has one exec file. I copied that file in a separate folder and then I want to see the file contents of it. 

I used "bloaty PSExpress".. It told me the size of components with _text etc symbols. But when I am using -d compileunits it is saying "missing debug info."..

What can I do to resolve it? Please guide.

Thanks in advance.

Regards.

**Comment by haberman** [comment]
The `-d compileunits` data source requires that debug info is available. You must compile with debugging info enabled `-g` or similar). There is some info here: https://github.com/google/bloaty/blob/master/doc/using.md#debugging-stripped-binaries
