### ISSUE TITLE
Overflow in vm range

### ISSUE THREAD

**Issue by zhanglistar** [google/bloaty#349]
Reproduce steps:
1. clone gluten project, `git clone https://github.com/oap-project/gluten.git`
2. compile libch.so, `cd gluten && bash -x ep/build-clickhouse/src/build_clickhouse.sh `
4. call bloaty, 
`bloaty cpp-ch/build/utils/extern-local-engine/libch.so -d compileunits`
Then got error:
`bloaty: Overflow in vm range, vmaddr=52654762, vmsize=18446744073709551369`

**Comment by younesr1** [comment]
@zhanglistar was there a resolution to this issue?
