### ISSUE TITLE
this tool support for windows?

### ISSUE THREAD

**Issue by calvinhxx** [google/bloaty#369]
build by cmake msvc
![image](https://github.com/google/bloaty/assets/35599730/efbe5ffb-3764-40bc-852a-f4c46b8f77af)
![image](https://github.com/google/bloaty/assets/35599730/8dcc86ae-cbab-41ef-8f05-b172f06f2994)
cmd tips like this: 
![image](https://github.com/google/bloaty/assets/35599730/2646b2f0-d7fd-4780-a330-9987d8e1cdaa)

**Comment by haberman** [comment]
The error message is telling you that Bloaty doesn't support the `compileunits` data source on Windows.

Supporting `compileunits` requires parsing debug information, and Bloaty only understands DWARF.
