### ISSUE TITLE
Suggestion: use LIEF for parsing?

### ISSUE THREAD

**Issue by MoritzFago** [google/bloaty#48]
Hello,

i read recently about bloaty and liked the idea. Today I read about [LIEF](https://lief.quarkslab.com), which claims, that they implemented a parser for ELF, PE and MachO executables. 

Maybe it helps, maybe not, close if not

**Comment by haberman** [comment]
Thanks for the suggestion! However I think Bloaty has some pretty specific requirements that LIEF (from a cursory look) doesn't appear to support. Most notably, Bloaty needs to know what byte range of the file each bit of data comes from. This applies to all file content, and even the headers! I think for now it's better for Bloaty to keep its own ELF parser.
