### ISSUE TITLE
Continue on "cant find file" error

### ISSUE THREAD

**Issue by mlekena** [google/bloaty#96]
Running Bloaty on a large list of object files and then having one object file that wast found stop the progression of the entire run is important, but sometimes no necessary. A continuation flag to let Bloaty know to progress on if it runs into a file it couldn't find/parse/read would be great. This would produce an inaccurate analysis of the total object sizes but with massive projects, this could be workable.

**Comment by haberman** [comment]
Sorry for the very late response! I think I would prefer to keep Bloaty's current behavior. I think the case where a missing input file is acceptable are somewhat rare. If I get a lot of requests for this, we can reconsider.
